# CPJ Theme Routes Configuration
# Upload this file via Ghost Admin > Settings > Labs > Routes

routes:
  /: index

collections:
  /essays/:
    permalink: /essays/{slug}/
    template: tag-essays
    filter: tag:essays

  /five-things/:
    permalink: /five-things/{slug}/
    template: tag-five-things
    filter: tag:five-things

  /radar/:
    permalink: /radar/{slug}/
    template: tag-radar
    filter: tag:radar

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
